/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type { ReactNode } from 'react'
import { useGLTF } from '@react-three/drei'
import {
  asPortfolioGltf,
  type ModelGroupProps,
} from '@/features/3d-scene/models/types/gltf.types'

export type About3DProps = ModelGroupProps & {
  children?: ReactNode
}

export function About3D({ children, ...props }: About3DProps) {
  const { nodes, materials } = asPortfolioGltf(
    useGLTF('/Models/Screens/AboutScreen.glb'),
  )
  return (
    <group {...props} dispose={null}>
      <group position={[8.168, 2.832, 0.58]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane015.geometry}
          material={materials.PC}
          scale={[1, 1, 0.7]}
        />
        {children}
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Screens/AboutScreen.glb')
