/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type { ReactNode } from 'react'
import { useGLTF } from '@react-three/drei'
import {
  asPortfolioGltf,
  type ModelGroupProps,
} from '@/features/3d-scene/models/types/gltf.types'

export type Contact3DProps = ModelGroupProps & {
  children?: ReactNode
}

export function Contact3D({ children, ...props }: Contact3DProps) {
  const { nodes, materials } = asPortfolioGltf(
    useGLTF('/Models/Screens/ContactScreen.glb'),
  )
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Phone001.geometry}
        material={materials.Screen}
        position={[-0.256, 2.962, -7.322]}
      >
        {children}
      </mesh>
    </group>
  )
}

useGLTF.preload('/Models/Screens/ContactScreen.glb')
