/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type { ReactNode } from 'react'
import { useGLTF } from '@react-three/drei'
import { useScaleAnimation } from '@/ui/hooks/useScaleAnimation'
import {
  asPortfolioGltf,
  type ModelGroupProps,
} from '@/features/3d-scene/models/types/gltf.types'

export type Menu3DProps = ModelGroupProps & {
  children?: ReactNode
  visible?: boolean
}

export function Menu3D({
  children,
  visible,
  ...props
}: Menu3DProps) {
  const { nodes, materials } = asPortfolioGltf(
    useGLTF('/Models/Screens/MenuScreen.glb'),
  )
  const scale = useScaleAnimation(visible ?? true, 1, 400)
  return (
    <group {...props} dispose={null} scale={scale}>
      <group position={[1.502, 0.344, 0.157]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034.geometry}
          material={materials.Screen}
        >
          {children}
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034_1.geometry}
          material={materials['MetalSilla.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Screens/MenuScreen.glb')
