/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import type { ReactNode } from 'react'
import { useGLTF } from '@react-three/drei'
import {
  asPortfolioGltf,
  type ModelGroupProps,
} from '@/features/3d-scene/models/types/gltf.types'

export type Skills3DProps = ModelGroupProps & {
  children?: ReactNode
}

export function Skills3D({ children, ...props }: Skills3DProps) {
  const { nodes, materials } = asPortfolioGltf(
    useGLTF('/Models/Screens/SkillsScreen.glb'),
  )
  return (
    <group {...props} dispose={null}>
      <group
        position={[-7.46, 3.935, -2.716]}
        rotation={[Math.PI / 2, 0, -1.171]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014.geometry}
          material={materials['MetalSilla.001']}
          scale={[0.8, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane014_1.geometry}
          material={materials.TV_Projects}
          scale={[0.8, 1, 1]}
        />
        <mesh>{children}</mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/Models/Screens/SkillsScreen.glb')
