/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";
import * as THREE from "three";
import {
  characterIntroSpeed,
  characterSitSpeed,
} from "@/core/constants/timing";
import type { CharacterProps } from "@/features/3d-scene/models/character/Character.types";
import { asPortfolioGltf } from "@/features/3d-scene/models/types/gltf.types";
import { useCharacterEyeDissolve } from "@/features/3d-scene/models/character/hooks/useCharacterEyeDissolve";
import { useSceneStore } from "@/store/sceneStore";

export function Character({
  introAnimation,
  sitAnimation,
  visible = true,
  dissolveEyes = false,
  ...props
}: CharacterProps) {
  const group = useRef<THREE.Group>(null);
  const gltf = useGLTF("/Models/Character.glb");
  const portfolioGltf = asPortfolioGltf(gltf);
  const { materials, animations } = portfolioGltf;
  const nodes = portfolioGltf.nodes as Record<string, THREE.SkinnedMesh>;
  const { names, mixer } = useAnimations(animations, group);
  const { eyesMaterialRef, initialEyeColor } =
    useCharacterEyeDissolve(dissolveEyes);
  const setCharacterAnimStarted = useSceneStore(
    (state) => state.setCharacterAnimStarted,
  );

  useEffect(() => {
    if (introAnimation) {
      const clip = animations.find((_, i) => names[i] === names[1]);
      if (!clip) return;

      const intro = mixer.clipAction(clip);
      if (intro) {
        intro.play().fadeIn(0).timeScale = characterIntroSpeed;
        setCharacterAnimStarted(true);
      }
    }

    if (sitAnimation) {
      const sitClip = animations.find((_, i) => names[i] === names[0]);
      const introClip = animations.find((_, i) => names[i] === names[1]);
      if (!sitClip || !introClip) return;

      const sit = mixer.clipAction(sitClip);
      const intro = mixer.clipAction(introClip);
      if (sit && intro) {
        intro.fadeOut(1);
        sit.play().fadeIn(0.5).timeScale = characterSitSpeed;
        sit.setLoop(THREE.LoopOnce, 1);
        sit.clampWhenFinished = true;
      }
    }
  }, [
    introAnimation,
    sitAnimation,
    names,
    setCharacterAnimStarted,
    animations,
    mixer,
  ]);

  return (
    <group ref={group} {...props} dispose={null} visible={visible}>
      <group name="Scene">
        <group
          name="Character"
          position={[0, 0, 0.786]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group name="Brazo1001">
            <skinnedMesh
              name="Cube020"
              geometry={nodes.Cube020.geometry}
              material={materials["Piel.001"]}
              skeleton={nodes.Cube020.skeleton}
              frustumCulled={false}
            />
            <skinnedMesh
              name="Cube020_1"
              geometry={nodes.Cube020_1.geometry}
              material={materials["Shirt.001"]}
              skeleton={nodes.Cube020_1.skeleton}
              frustumCulled={false}
            />
            <skinnedMesh
              name="Cube020_2"
              geometry={nodes.Cube020_2.geometry}
              material={materials["Manga.001"]}
              skeleton={nodes.Cube020_2.skeleton}
              frustumCulled={false}
            />
          </group>
          <group name="Brazo2001">
            <skinnedMesh
              name="Cube022"
              geometry={nodes.Cube022.geometry}
              material={materials["Piel.001"]}
              skeleton={nodes.Cube022.skeleton}
              frustumCulled={false}
            />
            <skinnedMesh
              name="Cube022_1"
              geometry={nodes.Cube022_1.geometry}
              material={materials["Shirt.001"]}
              skeleton={nodes.Cube022_1.skeleton}
              frustumCulled={false}
            />
            <skinnedMesh
              name="Cube022_2"
              geometry={nodes.Cube022_2.geometry}
              material={materials["Manga.001"]}
              skeleton={nodes.Cube022_2.skeleton}
              frustumCulled={false}
            />
          </group>
          <skinnedMesh
            name="Cabeza001"
            geometry={nodes.Cabeza001.geometry}
            material={materials["Piel.001"]}
            skeleton={nodes.Cabeza001.skeleton}
          />
          <skinnedMesh
            name="Cejas001"
            geometry={nodes.Cejas001.geometry}
            material={materials["Fade2.001"]}
            skeleton={nodes.Cejas001.skeleton}
          />
          <skinnedMesh
            name="Ojos001"
            geometry={nodes.Ojos001.geometry}
            skeleton={nodes.Ojos001.skeleton}
          >
            <meshStandardMaterial
              ref={eyesMaterialRef}
              color={initialEyeColor}
              transparent
            />
          </skinnedMesh>
          <group name="Pelo001">
            <skinnedMesh
              name="Sphere009"
              geometry={nodes.Sphere009.geometry}
              material={materials["Fade1.001"]}
              skeleton={nodes.Sphere009.skeleton}
            />
            <skinnedMesh
              name="Sphere009_1"
              geometry={nodes.Sphere009_1.geometry}
              material={materials["Fade2.001"]}
              skeleton={nodes.Sphere009_1.skeleton}
            />
            <skinnedMesh
              name="Sphere009_2"
              geometry={nodes.Sphere009_2.geometry}
              material={materials["Fade3.001"]}
              skeleton={nodes.Sphere009_2.skeleton}
            />
          </group>
          <group name="Piernas001">
            <skinnedMesh
              name="Cube023"
              geometry={nodes.Cube023.geometry}
              material={materials["Piel.001"]}
              skeleton={nodes.Cube023.skeleton}
            />
            <skinnedMesh
              name="Cube023_1"
              geometry={nodes.Cube023_1.geometry}
              material={materials["jean.001"]}
              skeleton={nodes.Cube023_1.skeleton}
            />
            <skinnedMesh
              name="Cube023_2"
              geometry={nodes.Cube023_2.geometry}
              material={materials["Medias.001"]}
              skeleton={nodes.Cube023_2.skeleton}
            />
          </group>
          <group name="Tenis001">
            <skinnedMesh
              name="Cube025"
              geometry={nodes.Cube025.geometry}
              material={materials["jean.001"]}
              skeleton={nodes.Cube025.skeleton}
            />
            <skinnedMesh
              name="Cube025_1"
              geometry={nodes.Cube025_1.geometry}
              material={materials["Cordones.001"]}
              skeleton={nodes.Cube025_1.skeleton}
            />
            <skinnedMesh
              name="Cube025_2"
              geometry={nodes.Cube025_2.geometry}
              material={materials["TenisBase.001"]}
              skeleton={nodes.Cube025_2.skeleton}
            />
            <skinnedMesh
              name="Cube025_3"
              geometry={nodes.Cube025_3.geometry}
              material={materials["Tenis2.001"]}
              skeleton={nodes.Cube025_3.skeleton}
            />
            <skinnedMesh
              name="Cube025_4"
              geometry={nodes.Cube025_4.geometry}
              material={materials["Tenis3.001"]}
              skeleton={nodes.Cube025_4.skeleton}
            />
          </group>
          <group name="Torzo2002">
            <skinnedMesh
              name="Cube031"
              geometry={nodes.Cube031.geometry}
              material={materials["Shirt.001"]}
              skeleton={nodes.Cube031.skeleton}
              frustumCulled={false}
            />
            <skinnedMesh
              name="Cube031_1"
              geometry={nodes.Cube031_1.geometry}
              material={materials["jean.001"]}
              skeleton={nodes.Cube031_1.skeleton}
              frustumCulled={false}
            />
          </group>
          <primitive object={portfolioGltf.nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Models/Character.glb");
