/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import {
  asPortfolioGltf,
  type ModelGroupProps,
} from '@/features/3d-scene/models/types/gltf.types'

export type ShelfProps = ModelGroupProps

export function Shelf({ ...props }: ShelfProps) {
  const { nodes, materials } = asPortfolioGltf(useGLTF('/Models/Shelf.glb'))
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bookshelf.geometry}
        material={materials.Shelf}
        position={[-7.914, 0, 2.2]}
        rotation={[-Math.PI, 1.227, -Math.PI]}>
        <group position={[-0.597, 0, 8.193]} rotation={[Math.PI, -1.227, Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DS_Cube033_1.geometry}
            material={materials['1A1A1A']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DS_Cube033_1_1.geometry}
            material={materials['80DEEA']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DS_Cube033_1_2.geometry}
            material={materials.F44336}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DS_Cube033_1_3.geometry}
            material={materials['8BC34A.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DS_Cube033_1_4.geometry}
            material={materials.DD9944}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DS_Cube033_1_5.geometry}
            material={materials['039BE5']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DS_Cube033_1_6.geometry}
            material={materials['78909C']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.DS_Cube033_1_7.geometry}
            material={materials['455A64.002']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Books.geometry}
          material={materials['Material.006']}
          position={[-0.282, 3.695, 0.089]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Cat_01(1)'].geometry}
          material={materials['Material.007']}
          position={[-0.597, 0, 8.193]}
          rotation={[Math.PI, -1.227, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Horse.geometry}
          material={materials.Statue}
          position={[0.011, 1.328, 0.058]}
          rotation={[-Math.PI / 2, 0, 0.803]}
        />
        <group position={[-0.597, 0, 8.193]} rotation={[Math.PI, -1.227, Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh001'].geometry}
            material={materials.lambert2SG}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh001_1'].geometry}
            material={materials['lambert3SG.001']}
          />
        </group>
        <group position={[-0.929, 3.981, 0.002]} rotation={[0, -0.868, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['plant-Mesh002'].geometry}
            material={materials['None.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['plant-Mesh002_1'].geometry}
            material={materials.Matera2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['plant-Mesh002_2'].geometry}
            material={materials.Plant}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['plant-Mesh002_3'].geometry}
            material={materials.Shelf}
          />
        </group>
        <group position={[-0.141, 0.364, 0.002]} rotation={[0, -0.868, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['plant-Mesh003'].geometry}
            material={materials['None.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['plant-Mesh003_1'].geometry}
            material={materials['mat8.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['plant-Mesh003_2'].geometry}
            material={materials['Screen.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['plant-Mesh003_3'].geometry}
            material={materials.Shelf}
          />
        </group>
        <group position={[-0.597, 0, 8.193]} rotation={[Math.PI, -1.227, Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh002'].geometry}
            material={materials['mat21.002']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh002_1'].geometry}
            material={materials['mat22.003']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh002_2'].geometry}
            material={materials.mat15}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Node-Mesh002_3'].geometry}
            material={materials.mat24}
          />
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/Models/Shelf.glb')